services:
  - type: web
    name: beacon-backend
    env: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        value: https://beacon-9oyd.onrender.com
      - key: ALLOWED_ORIGINS
        value: "*"

