export const NXA_ENERGY_ORB_VERTEX_SHADER = "attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}";

export const NXA_ENERGY_ORB_CONFIGURABLE_FRAGMENT_SHADER = [
  "precision highp float;",
  "uniform float uT;uniform vec2 uR;uniform vec2 uMouse;",
  "uniform float uSmokeScale;uniform float uSmokeStrength;uniform float uSmokeSpeed;",
  "uniform float uHue;uniform float uSaturation;uniform float uGlow;",
  "float hash(vec3 p){p=fract(p*0.3183099+vec3(0.1,0.2,0.3));p*=17.0;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));}",
  "float noise(vec3 x){vec3 i=floor(x);vec3 f=fract(x);f=f*f*(3.0-2.0*f);",
  " return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),",
  " mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}",
  "float fbm(vec3 p){float v=0.0;float a=0.5;for(int i=0;i<5;i++){v+=a*noise(p);p=p*2.03+vec3(1.7);a*=0.5;}return v;}",
  "vec3 gradeColor(vec3 color){",
  " float luminance=dot(color,vec3(0.2126,0.7152,0.0722));",
  " color=mix(vec3(luminance),color,uSaturation);",
  " vec3 axis=normalize(vec3(1.0));",
  " return max(vec3(0.0),color*cos(uHue)+cross(axis,color)*sin(uHue)+axis*dot(axis,color)*(1.0-cos(uHue)));",
  "}",
  "void main(){",
  " vec2 uv=(gl_FragCoord.xy-0.5*uR)/min(uR.x,uR.y);",
  " float r=length(uv);",
  " float R=0.31;",
  " float aa=max(0.006, 3.5/min(uR.x,uR.y));",
  " float sphereEdge=smoothstep(R+aa,R-aa,r);",
  " vec3 sphereCol=vec3(0.0);",
  " float sphereAlpha=0.0;",
  " if(r<R+aa){",
  "   float clampedR=min(r,R-0.0001);",
  "   float z=sqrt(max(0.0,R*R-clampedR*clampedR));",
  "   vec3 n=normalize(vec3(uv,z));",
  "   float ca=uT*0.15; mat3 rot=mat3(cos(ca),0.,sin(ca),0.,1.,0.,-sin(ca),0.,cos(ca));",
  "   vec3 sp=rot*n;",
  "   sp.xy += (uMouse - vec2(0.5)) * 0.25;",
  "   float smokeTime=uT*uSmokeSpeed;",
  "   float f1=fbm(sp*(2.6*uSmokeScale)+vec3(0.0,smokeTime*0.12,0.0));",
  "   float f2=fbm(sp*(4.5*uSmokeScale)-vec3(smokeTime*0.08,0.0,smokeTime*0.05)+f1*1.8);",
  "   float veil=smoothstep(0.35,0.75,f2);",
  "   vec3 deep=vec3(0.04,0.02,0.12);",
  "   vec3 mid=vec3(0.22,0.16,0.55);",
  "   vec3 bright=vec3(0.62,0.60,0.98);",
  "   sphereCol=mix(deep,mid,f1*1.2);",
  "   sphereCol=mix(sphereCol,bright,clamp(veil*0.65*uSmokeStrength,0.0,1.0));",
  "   float fres=pow(1.0-z/R,2.2);",
  "   sphereCol+=vec3(0.55,0.55,1.0)*fres*1.1*uGlow;",
  "   float top=pow(max(dot(n,normalize(vec3(0.0,0.7,0.7))),0.0),3.0);",
  "   sphereCol+=vec3(0.45,0.42,0.9)*top*0.35*uGlow;",
  "   float rim=smoothstep(R-0.03,R,r);",
  "   sphereCol+=vec3(0.6,0.58,1.0)*rim*0.6*uGlow;",
  "   sphereAlpha=1.0;",
  " }",
  " float glowFactor=clamp(exp(-(max(0.0,r-R))*14.0),0.0,1.0);",
  " vec3 glowCol=vec3(0.55,0.52,1.0)*glowFactor*0.8*uGlow;",
  " float glowAlpha=glowFactor*0.85;",
  " vec3 finalCol=mix(glowCol,sphereCol,sphereEdge);",
  " float finalAlpha=mix(glowAlpha,sphereAlpha,sphereEdge);",
  " finalCol=gradeColor(finalCol);",
  " gl_FragColor=vec4(finalCol,finalAlpha);",
  "}",
].join("\n");
